name: Snyk

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  security:
    uses: guardian/.github/.github/workflows/sbt-node-snyk.yml@main
    with:
      DEBUG: true
      ORG: guardian-investigations
      SKIP_NODE: false
      SKIP_PYTHON: false
      PIPFILES: Pipfile
    secrets:
       SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
