# This action is just a test
name: Snyk

on: push

jobs:
  security:
    uses: guardian/.github/.github/workflows/sbt-node-snyk.yml@js/snyk-prune-dupes
    with:
      DEBUG: true
      ORG: guardian-test
      SKIP_NODE: false
      SKIP_PYTHON: false
    secrets:
       SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
